### -------------------- List --------------------
GET http://localhost:8080/transaction?page=3

### -------------------- List by ID --------------------
GET http://localhost:8080/transaction/100071

### -------------------- Create 1 --------------------
POST http://localhost:8080/transaction
Content-Type: application/json

{
  "date": "09/11/2023 09:15",
  "client": "Marcos",
  "description": "",
  "productList": [
    {
      "id": 10037,
      "amount": 2,
      "description": ""
    },
    {
      "id": 10012,
      "amount": 2,
      "description": ""
    },
    {
      "id": 10001,
      "amount": 2,
      "description": ""
    },
    {
      "id": 10101,
      "amount": 50,
      "description": ""
    }
  ]
}
### -------------------- Create 2 --------------------
POST http://localhost:8080/transaction
Content-Type: application/json

{
  "date": "09/11/2023 11:35",
  "client": "Lucas",
  "description": "",
  "productList": [
    {
      "id": 10023,
      "amount": 0,
      "description": ""
    }
  ]
}

### -------------------- Refound Product --------------------
PUT http://localhost:8080/transaction
Content-Type: application/json

{
  "transactionId": 100143,
  "listRefoundProduct": [
    {
      "purchasedItemId": 1000537,
      "amountRefunded": 0,
      "reason": "UNHAPPY_COSTUMER",
      "returnedToStock": true,
      "description": "cliente não gostou."
    }
  ]
}
### -------------------- Refound Product 2 --------------------
PUT http://localhost:8080/transaction
Content-Type: application/json

{
  "transactionId": 100071,
  "listRefoundProduct": [
    {
      "purchasedItemId": 1000246,
      "amountRefunded": 1,
      "reason": "UNHAPPY_COSTUMER",
      "returnedToStock": true,
      "description": "cliente não precisou de duas lixadeiras."
    },
    {
      "purchasedItemId": 1000248,
      "amountRefunded": 2,
      "reason": "PRODUCT_DEFECT",
      "returnedToStock": false,
      "description": "parafuso com defeito na rosca"
    },
    {
      "purchasedItemId": 1000245,
      "amountRefunded": 1,
      "reason": "PRODUCT_DEFECT",
      "returnedToStock": false,
      "description": "cabeçote com amassado"
    },
    {
      "purchasedItemId": 1000247,
      "amountRefunded": 1,
      "reason": "UNHAPPY_COSTUMER",
      "returnedToStock": true,
      "description": "cliente não gostou do corte da tesoura"
    }
  ]
}
### -------------------- Detail Refound by transactionID --------------------
GET http://localhost:8080/transaction/refound/100071